USE mysql;

DROP FUNCTION IF EXISTS TO_BASE64;
DROP FUNCTION IF EXISTS FROM_BASE64;

CREATE FUNCTION TO_BASE64 RETURNS STRING SONAME 'base64.so';
CREATE FUNCTION FROM_BASE64 RETURNS STRING SONAME 'base64.so';
